<!DOCTYPE html>
<html class="no-js" lang="pt-br">

<head>
	<title>Lothus {PHP}</title>

	<meta charset="UTF-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1"/>

	<!-- CSS -->
	<link rel="stylesheet" type="text/css" href="<?= CSS ?>style.css" />

	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
		<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>

	<body>
        <header>
            <h1>Exemplo Lothus{PHP}</h1>
        </header>

        <hr>

        <ul>
            <li><a href="<?= URL ?>todo">Lista</a></li>
            <li><a href="<?= URL ?>todo/inserir">Inserir</a></li>
        </ul>

		<div class="container">
			{conteudo}
		</div>

	</body>

</html>